name: Update EPG Files

on:
  schedule:
    - cron: '0 * * * *'  # Ogni ora, al minuto 0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x backend/scripts/epg.sh

      - name: Run EPG update script and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main
          
          ./backend/scripts/epg.sh

          # ❌ Escludi file troppo grandi prima del commit
          find backend/epg/xml -type f \( -name "*US_LOCALS2.xml" -o -name "*ALL_SOURCES1.xml" \) -exec rm -f {} \;

          # ✅ Commit e push solo se ci sono cambiamenti
          git add backend/epg/xml/*.xml backend/epg/epg-sources.json
          git diff --cached --quiet || git commit -m "Update EPG files"
          git push || echo "ℹ️ Nessun push necessario"
