name: Update EPG Files

on:
  schedule:
    - cron: '0 * * * *'  # Ogni ora
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x backend/scripts/epg.sh

      - name: Run EPG update script and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main
          ./backend/scripts/epg.sh
          git add -A
          git commit -m "Update EPG files" || echo "ℹ️ Nessun cambiamento da committare"
          git push || echo "ℹ️ Nessun push necessario"
