name: Push Docker image to GHCR

on:
  push:
    tags:        
      - '*'  # Trigger su qualsiasi tag pushato

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Print latest tag
        run: echo ${{ steps.get-latest-tag.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get repository and username
        run: |
          echo "USERNAME=$(echo ${GITHUB_REPOSITORY%/*} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "Username: $USERNAME"
          echo "Repository Name: $REPOSITORY_NAME"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/${{ env.USERNAME }}/${{ env.REPOSITORY_NAME }}:${{ steps.get-latest-tag.outputs.tag }},ghcr.io/${{ env.USERNAME }}/${{ env.REPOSITORY_NAME }}:latest