name: Visits

on:
  schedule:
    - cron: '*/30 * * * *'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Scarica e genera visits.json
      run: |
        curl -s https://www.counters-free.net/count/hpvh > raw.txt

        line=$(grep "document.write" raw.txt | sed -n "s/.*document.write('\(.*\)');.*/\1/p")
        html=$(echo "$line" | sed 's/&lt;/</g; s/&gt;/>/g; s/&quot;/\"/g; s/&apos;/'"'"'/g; s/&amp;/\&/g')
        total=$(echo "$html" | grep -o "Total: [0-9]*" | cut -d':' -f2 | xargs)

        echo "Numero estratto: $total"
        mkdir -p backend/info
        echo "{ \"visits\": $total }" > backend/info/visits.json

    - name: Commit and push if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        if git diff --quiet backend/info/visits.json; then
          echo "Nessuna modifica, skip commit."
        else
          git add backend/info/visits.json
          git commit -m "🔄 Update visits.json: $(date -u '+%Y-%m-%d %H:%M UTC')"
          git push
        fi
